name: Build and Test .NET Project

on:
  push:
    branches:
      - main  # Or your default branch
  pull_request:
    branches:
      - main  # Or your default branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x', '7.0.x']  # You can adjust these versions as needed

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up the .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build project
        run: dotnet build --configuration Release

      # Run unit tests
      - name: Run unit tests
        run: dotnet test --configuration Release
